In [1]:
import pandas as pd
import numpy as np

In [50]:
MATR = np.array([
    [-1, 1, 0, 0, 0],
    [-2,-1, 1, 1, 0],
    [ 0, 0,-1, 0, 1]
])

MATR_PLUS = np.where(MATR < 0, -MATR, 0)
print(MATR_PLUS)

[[1 0 0 0 0]
 [2 1 0 0 0]
 [0 0 1 0 0]]


In [51]:
np.linalg.inv(MATR @ MATR.T) @ MATR

array([[-0.375     ,  0.625     , -0.04166667, -0.08333333, -0.04166667],
       [-0.25      , -0.25      ,  0.08333333,  0.16666667,  0.08333333],
       [-0.125     , -0.125     , -0.45833333,  0.08333333,  0.54166667]])

In [52]:
P = np.prod(np.array([2,3,4,5,1]) ** MATR_PLUS, axis=1)

print(P)    # Получаем численные значения скоростей рекаций (без констант k) в момент времени

[ 2 12  4]


In [53]:
print(MATR.T)

[[-1 -2  0]
 [ 1 -1  0]
 [ 0  1 -1]
 [ 0  1  0]
 [ 0  0  1]]


In [56]:
A = MATR.T * P
print(A)

[[ -2 -24   0]
 [  2 -12   0]
 [  0  12  -4]
 [  0  12   0]
 [  0   0   4]]


In [59]:
np.linalg.inv(A.T @ A) @ A.T

array([[-0.1875    ,  0.3125    , -0.02083333, -0.04166667, -0.02083333],
       [-0.02083333, -0.02083333,  0.00694444,  0.01388889,  0.00694444],
       [-0.03125   , -0.03125   , -0.11458333,  0.02083333,  0.13541667]])